/**
 * amis-editor v5.2.5-beta.3
 * Copyright 2018-2023 @fex
 */

'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

require('amis');
require('./locale/en-US.js');
require('./locale/zh-CN.js');
var amisEditorCore = require('amis-editor-core');
require('./tpl/common.js');
require('./tpl/remark.js');
require('./tpl/horizontal.js');
require('./tpl/api.js');
require('./tpl/options.js');
require('./tpl/validations.js');
require('./tpl/style.js');
require('./tpl/layout.js');
require('./plugin/Others/Action.js');
require('./plugin/Others/TableCell.js');
require('./plugin/Form/InputArray.js');
require('./plugin/Form/ButtonGroupSelect.js');
require('./plugin/Form/ButtonToolbar.js');
require('./plugin/Form/ChainedSelect.js');
require('./plugin/Form/Checkbox.js');
require('./plugin/Form/Checkboxes.js');
require('./plugin/Form/InputCity.js');
require('./plugin/Form/InputColor.js');
require('./plugin/Form/Combo.js');
require('./plugin/Form/ConditionBuilder.js');
require('./plugin/Form/Control.js');
require('./plugin/Form/InputDate.js');
require('./plugin/Form/InputDateRange.js');
require('./plugin/Form/InputDateTime.js');
require('./plugin/Form/InputDateTimeRange.js');
require('./plugin/Form/DiffEditor.js');
require('./plugin/Form/CodeEditor.js');
require('./plugin/Form/InputEmail.js');
require('./plugin/Form/FieldSet.js');
require('./plugin/Form/InputFile.js');
require('./plugin/Form/Form.js');
require('./plugin/Form/Formula.js');
require('./plugin/Form/Group.js');
require('./plugin/Form/Hidden.js');
require('./plugin/Form/InputImage.js');
require('./plugin/Form/InputGroup.js');
require('./plugin/Form/Item.js');
require('./plugin/Form/ListSelect.js');
require('./plugin/Form/LocationPicker.js');
require('./plugin/Form/UUID.js');
require('./plugin/Form/MatrixCheckboxes.js');
require('./plugin/Form/InputMonth.js');
require('./plugin/Form/InputMonthRange.js');
require('./plugin/Form/NestedSelect.js');
require('./plugin/Form/InputNumber.js');
require('./plugin/Form/InputPassword.js');
require('./plugin/Form/InputQuarter.js');
require('./plugin/Form/InputQuarterRange.js');
require('./plugin/Form/Picker.js');
require('./plugin/Form/Radios.js');
require('./plugin/Form/InputRange.js');
require('./plugin/Form/InputRating.js');
require('./plugin/Form/InputRepeat.js');
require('./plugin/Form/InputRichText.js');
require('./plugin/Form/Select.js');
require('./plugin/Form/Static.js');
require('./plugin/Form/InputSubForm.js');
require('./plugin/Form/Switch.js');
require('./plugin/Form/InputTable.js');
require('./plugin/Form/InputTag.js');
require('./plugin/Form/InputText.js');
require('./plugin/Form/TabsTransfer.js');
require('./plugin/Form/Textarea.js');
require('./plugin/Form/Transfer.js');
require('./plugin/Form/InputTime.js');
require('./plugin/Form/InputTimeRange.js');
require('./plugin/Form/InputTree.js');
require('./plugin/Form/TreeSelect.js');
require('./plugin/Form/InputURL.js');
require('./plugin/Form/InputYear.js');
require('./plugin/Form/InputYearRange.js');
require('./plugin/Form/InputExcel.js');
require('./plugin/Form/InputKV.js');
require('./plugin/Alert.js');
require('./plugin/Audio.js');
require('./plugin/Avatar.js');
require('./plugin/Button.js');
require('./plugin/ButtonGroup.js');
require('./plugin/Breadcrumb.js');
require('./plugin/Card.js');
require('./plugin/Card2.js');
require('./plugin/Cards.js');
require('./plugin/Carousel.js');
require('./plugin/Chart.js');
require('./plugin/Collapse.js');
require('./plugin/CollapseGroup.js');
require('./plugin/Container.js');
require('./plugin/CRUD.js');
require('./plugin/Custom.js');
require('./plugin/CustomRegion.js');
require('./plugin/Date.js');
require('./plugin/Datetime.js');
require('./plugin/Dialog.js');
require('./plugin/Divider.js');
require('./plugin/Drawer.js');
require('./plugin/DropDownButton.js');
require('./plugin/Each.js');
require('./plugin/Flex.js');
var Grid = require('./plugin/Grid.js');
require('./plugin/HBox.js');
require('./plugin/IFrame.js');
require('./plugin/Image.js');
require('./plugin/Images.js');
require('./plugin/Json.js');
require('./plugin/Link.js');
require('./plugin/List.js');
require('./plugin/ListItem.js');
require('./plugin/Log.js');
require('./plugin/Mapping.js');
require('./plugin/Markdown.js');
require('./plugin/Nav.js');
require('./plugin/Operation.js');
require('./plugin/Page.js');
require('./plugin/Pagination.js');
require('./plugin/Panel.js');
require('./plugin/Plain.js');
require('./plugin/Progress.js');
require('./plugin/Property.js');
require('./plugin/QRCode.js');
require('./plugin/Reset.js');
require('./plugin/Service.js');
require('./plugin/Status.js');
require('./plugin/Steps.js');
require('./plugin/Sparkline.js');
require('./plugin/Submit.js');
require('./plugin/Table.js');
require('./plugin/Table2.js');
require('./plugin/TableCell2.js');
require('./plugin/Tabs.js');
require('./plugin/Tasks.js');
require('./plugin/Time.js');
require('./plugin/Timeline.js');
require('./plugin/Tpl.js');
require('./plugin/Tag.js');
require('./plugin/AnchorNav.js');
require('./plugin/Video.js');
require('./plugin/Wizard.js');
require('./plugin/Wrapper.js');
require('./plugin/TooltipWrapper.js');
require('./plugin/TableView.js');
require('./plugin/CodeView.js');
require('./plugin/WebComponent.js');
require('./plugin/CRUD2.js');
require('./plugin/ColumnToggler.js');
require('./plugin/Layout/Layout_sorption_container.js');
require('./plugin/Layout/Layout_fixed.js');
require('./plugin/Layout/Layout_free_container.js');
require('./renderer/OptionControl.js');
require('./renderer/NavSourceControl.js');
require('./renderer/NavBadgeControl.js');
require('./renderer/NavDefaultActive.js');
require('./renderer/MapSourceControl.js');
require('./renderer/TimelineItemControl.js');
require('./renderer/APIControl.js');
require('./renderer/ValidationControl.js');
require('./renderer/ValidationItem.js');
require('./renderer/SwitchMoreControl.js');
require('./renderer/StatusControl.js');
require('./renderer/FormulaControl.js');
require('./renderer/ExpressionFormulaControl.js');
require('./renderer/textarea-formula/TextareaFormulaControl.js');
require('./renderer/DateShortCutControl.js');
require('./renderer/BadgeControl.js');
require('./renderer/style-control/BoxModel.js');
require('./renderer/style-control/Font.js');
require('./renderer/style-control/Border.js');
require('./renderer/style-control/BoxShadow.js');
require('./renderer/style-control/Background.js');
require('./renderer/style-control/Display.js');
require('./renderer/style-control/InsetBoxModel.js');
require('./renderer/RangePartsControl.js');
require('./renderer/DataBindingControl.js');
require('./renderer/DataMappingControl.js');
require('./renderer/DataPickerControl.js');
require('./renderer/FeatureControl.js');
require('./renderer/event-control/index.js');
require('./renderer/TreeOptionControl.js');
require('./renderer/TransferTableControl.js');
require('./renderer/style-control/ThemeClassName.js');
require('amis-theme-editor/lib/renderers/Border');
require('amis-theme-editor/lib/renderers/ColorPicker');
require('amis-theme-editor/lib/renderers/Font');
require('amis-theme-editor/lib/renderers/PaddingAndMargin');
require('amis-theme-editor/lib/renderers/Radius');
require('amis-theme-editor/lib/renderers/Shadow');
require('amis-theme-editor/lib/renderers/Size');
require('amis-theme-editor/lib/renderers.css');
var BaseControl = require('./component/BaseControl.js');
require('./icons/index.js');



Object.defineProperty(exports, 'Icon', {
	enumerable: true,
	get: function () { return amisEditorCore.Icon; }
});
exports.GridPlugin = Grid.GridPlugin;
exports.BUTTON_DEFAULT_ACTION = BaseControl.BUTTON_DEFAULT_ACTION;
exports.BaseLabelMark = BaseControl.BaseLabelMark;
exports.formItemControl = BaseControl.formItemControl;
exports.remarkTpl = BaseControl.remarkTpl;
Object.keys(amisEditorCore).forEach(function (k) {
	if (k !== 'default' && !exports.hasOwnProperty(k)) Object.defineProperty(exports, k, {
		enumerable: true,
		get: function () { return amisEditorCore[k]; }
	});
});
